version: "3"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  nginx:
    image: nginx:latest
    depends_on:
      - api
      - client
    restart: always    
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '4051:80'
  api:
    depends_on: 
      - mongo
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes: 
      - /app/node_modules
      - ./server:/app
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - PORT=5000
      - MONGODB_URL=mongodb://127.0.0.1:27017/trucks-db
      - JWT_SECRET=clientsecretToChange
  client:
    stdin_open: true
    build:  
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
      